import fixtureJson from '@/fixtures/timemachine/jul05.json';
import type { TimeMachineFixture } from './types';

/** Booth fixture — generated by scripts/export_timemachine_fixture.py from ClickHouse. */
export const boothFixture = fixtureJson as unknown as TimeMachineFixture;
